### ISSUE TITLE
Confía en el user input

### ISSUE THREAD

**Issue by juzalt** [malerey/tp2#1]
Muy buen programa, me divertí jugándolo y amé que uses los posters de las científicas mujeres.
Bueno, el issue que encontré betatesteándolo es que el programa me permite insertar lo que yo quiera en el campo de mi nombre.
Esto causa que si inserto esto por ejemplo:

`" value="" type="text"> <button id="namebutton" onclick="enviar()">Enviar</button></div></div></div></div></div>something</body>`

Modifico el cuerpo del HTML para que diga something.
No sé cómo solucionarlo. Se me ocurre limitar los carácteres que el usuario puede usar o aunque sea limitar la cantidad, pero la verdad es que no sé si eso sería una buena práctica. Soy muy novato en la programación. 

![screenshot from 2018-05-08 01-13-10](https://user-images.githubusercontent.com/9487486/39736018-0134158a-525d-11e8-8438-766f553c79ba.png)

**Comment by malerey** [comment]
¡Muchas gracias!  Es un tema del que soy consciente, lo hablé con mi profe. Aún no llegamos al punto de validar inputs, pero espero que lo hagamos pronto!
